### ISSUE TITLE
kotlinx.serialization.MissingFieldException: Field 'AuthenticationResult' is required for type with serial name 

### ISSUE THREAD

**Issue by ynsok** [Liftric/cognito-idp#52]
Hi,

I'm using this library on the multiplatform project, but unfortunately, I'm receiving an error 

`kotlinx.serialization.MissingFieldException: Field 'AuthenticationResult' is required for type with serial name 'com.liftric.cognito.idp.core.SignInResponse', but it was missing`
@tknoelle  @lammertw @AndreasBoehm @tokawpl

**Comment by gaebel** [comment]
Hi @ynsok,

I just had a quick look into the [documentation](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html) for the sign in request, which states:

> The result of the authentication response. This result is only returned if the caller doesn't need to pass another challenge. If the caller does need to pass another challenge before it gets tokens, ChallengeName, ChallengeParameters, and Session are returned.

The parameter should actually be optional. The [request to respond to the authentication challenge](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html) is not implemented.

We've only implemented the requests needed for our setup. You're free to open a PR with the needed changes, otherwise I can tackle this some time next week.

**Comment by ynsok** [comment]
Hi @gaebel 
Is there an option to log in without needing another challenge? or how to pass the challenge?

**Comment by gaebel** [comment]
It depends on your user pool configuration, it's possible to only require username and password. We fixed the SignInResponse and added the RespondToAuthChallenge route in #55 (which adds support for mfa).
